---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n0
  ip: 10.128.0.2
  join_ip: 10.128.0.3
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n1
  ip: 10.128.0.3
  join_ip: 10.128.0.2
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n2
  ip: 10.128.0.4
  join_ip: 10.128.0.2
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n3
  ip: 10.128.0.5
  join_ip: 10.128.0.2
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...
