---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n0
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n0
  ip: 172.16.1.3
  join_ip: 172.16.1.4
  labels:
    dynamic:
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n1
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n1
  ip: 172.16.1.4
  join_ip: 172.16.1.3
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n2
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n2
  ip: 172.16.1.8
  join_ip: 172.16.1.3
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
---
schema: promenade/KubernetesNode/v1
metadata:
  schema: metadata/Document/v1
  name: n3
  layeringDefinition:
    abstract: false
    layer: site
data:
  hostname: n3
  ip: 172.16.1.5
  join_ip: 172.16.1.3
  labels:
    static:
      - node-role.kubernetes.io/master=
    dynamic:
      - calico-etcd=enabled
      - kubernetes-apiserver=enabled
      - kubernetes-controller-manager=enabled
      - kubernetes-etcd=enabled
      - kubernetes-scheduler=enabled
      - ucp-control-plane=enabled
...
